// packages/web-component-library-stencil/src/components/top-task-nav.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-top-task-nav',
  styleUrl: 'top-task-nav.scss',
  shadow: true,
})
export class TopTaskNav {
  render() {
    // TODO: Add accessible name for navigation landmark,
    // using `aria-labelledby` and a heading.
    return (
      <nav class="utrecht-toptask-nav utrecht-toptask-nav--grid">
        <slot></slot>
      </nav>
    );
  }
}

// packages/storybook-css/src/ToptaskNav.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2022 Gemeente Utrecht
 * Copyright (c) 2022 Frameless B.V.
 */

import clsx from 'clsx';
import React, { HTMLAttributes, PropsWithChildren } from 'react';

export interface ToptaskNavProps extends PropsWithChildren<HTMLAttributes<HTMLElement>> {
  grid?: boolean;
}

export const ToptaskNav = ({ children, grid }: ToptaskNavProps) => (
  <div className={clsx('utrecht-toptask-nav', grid && 'utrecht-toptask-nav--grid')}>{children}</div>
);
