// packages/web-component-library-stencil/src/components/top-task-link.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-top-task-link',
  styleUrl: 'top-task-link.scss',
  shadow: true,
})
export class TopTaskLink {
  @Prop() external?: boolean;
  @Prop() href: string;
  @Prop() target?: string;
  render() {
    return (
      <a
        class="utrecht-toptask-link"
        href={this.href}
        rel={this.external ? 'external noopener noreferrer' : undefined}
        target={this.target}
      >
        <span class="utrecht-toptask-link__icon">
          <slot name="icon"></slot>
        </span>
        <span class="utrecht-toptask-link__title">
          <slot></slot>
        </span>
      </a>
    );
  }
}

// packages/storybook-css/src/ToptaskLink.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2022 Gemeente Utrecht
 * Copyright (c) 2022 Frameless B.V.
 */

import clsx from 'clsx';
import React, { AnchorHTMLAttributes, PropsWithChildren, ReactNode } from 'react';

export interface ToptaskLinkProps extends PropsWithChildren<AnchorHTMLAttributes<HTMLAnchorElement>> {
  focus?: boolean;
  focusVisible?: boolean;
  hover?: boolean;
  href: string;
  icon?: ReactNode;
}

export const ToptaskLink = ({
  className,
  focus,
  focusVisible,
  hover,
  href,
  icon,
  children,
  ...restProps
}: ToptaskLinkProps) => (
  <a
    href={href}
    className={clsx(
      'utrecht-toptask-link',
      {
        'utrecht-toptask-link--hover': hover,
        'utrecht-toptask-link--focus': focus,
        'utrecht-toptask-link--focus-visible': focusVisible,
      },
      className,
    )}
    {...restProps}
  >
    {icon && <span className="utrecht-toptask-link__icon">{icon}</span>}
    <span className="utrecht-toptask-link__title">{children}</span>
  </a>
);
