// packages/storybook-react/config/preview.jsx
import { addonStatus } from '@utrecht/storybook-helpers/src/addon-status';
import { addonViewport } from '@utrecht/storybook-helpers/src/addon-viewport';
// import { withTests } from '@storybook/addon-jest';
// import results from '@utrecht/component-library-react/dist/.jest-test-results.json';
import '@utrecht/design-tokens/dist/index.css';
import '@utrecht/storybook-helpers/src/storybook-docs.scss';

export const decorators = [
  (Story) => <div className="utrecht-document utrecht-theme">{Story()}</div>,
  // withTests({ results }),
];

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: {
    // Show code by default.
    // Stories without concise code snippets can hide the code at Story level.
    source: {
      state: 'open',
    },
  },
  ...addonStatus,
  ...addonViewport,
};

// packages/storybook-vue/config/preview.jsx
import { addonStatus } from '@utrecht/storybook-helpers/src/addon-status';
import { addonViewport } from '@utrecht/storybook-helpers/src/addon-viewport';
import '@utrecht/component-library-vue/dist/style.css';
import '@utrecht/design-tokens/dist/index.css';
import '@utrecht/storybook-helpers/src/storybook-docs.scss';
import Vue from 'vue'
import '@utrecht/component-library-vue/dist/store/index';

export const decorators = [
  (story) => ({
    components: { story },
    template: '<div class="utrecht-theme"><story /></div>',
  }),
  // withTests({ results }),
];


// provide('store', store);
Vue.provide('store', store);

export const parameters = {
  ...addonStatus,
  ...addonViewport,
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: {
    // Show code by default.
    // Stories without concise code snippets can hide the code at Story level.
    source: {
      state: 'open',
    },

    // container: ({ children }) => (
    //   <div className="utrecht-document utrecht-theme">
    //     <div className="utrecht-article">{children}</div>
    //   </div>
    // ),
  },
};
