// packages/web-component-library-stencil/src/components/number-value.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-number-value',
  styleUrl: 'number-value.scss',
  shadow: true,
})
export class NumberValue {
  @Prop() value: number | string;
  render() {
    const { value } = this;
    return typeof value === 'number' || typeof value === 'string' ? (
      // <data value={String(value)}>
      <data data-value={String(value)}>
        <slot></slot>
      </data>
    ) : (
      <span>
        <slot></slot>
      </span>
    );
  }
}

// packages/storybook/stories/components/NumberValue.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2022 Gemeente Utrecht
 * Copyright (c) 2022 Frameless B.V.
 */
import clsx from 'clsx';
import React from 'react';

export const defaultArgs = {
  appearance: '',
  textContent: '',
  value: '',
};

export const NumberValue = ({
  appearance = defaultArgs.appearance,
  textContent = defaultArgs.textContent,
  value = defaultArgs.value,
}) => {
  const className = clsx(
    'utrecht-value-number',
    appearance === 'negative' && 'utrecht-value-number--negative',
    appearance === 'positive' && 'utrecht-value-number--positive',
  );
  return value ? (
    <data value={String(value)} className={className}>
      {textContent}
    </data>
  ) : (
    <span className={className}>{textContent}</span>
  );
};

export default NumberValue;
