// packages/web-component-library-stencil/src/components/backdrop.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'utrecht-backdrop',
  styleUrl: 'backdrop.scss',
  shadow: true,
})
export class Backdrop {
  @Prop() viewport: boolean;
  render() {
    const { viewport } = this;
    return (
      <div class={clsx('utrecht-backdrop', viewport && 'utrecht-backdrop--viewport')}>
        <slot />
      </div>
    );
  }
}

// packages/component-library-react/src/Backdrop.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type BackdropProps = HTMLAttributes<HTMLDivElement>;

export const Backdrop = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<BackdropProps>, ref: ForwardedRef<HTMLDivElement>) => (
    <div {...restProps} ref={ref} className={clsx('utrecht-backdrop', className)}>
      {children}
    </div>
  ),
);

Backdrop.displayName = 'Backdrop';
