// packages/web-component-library-stencil/src/components/code-block.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-code-block',
  styleUrl: 'code-block.scss',
  shadow: true,
})
export class CodeBlock {
  render() {
    return (
      <pre class="utrecht-code-block">
        <slot></slot>
      </pre>
    );
  }
}

// packages/component-library-react/src/CodeBlock.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type CodeBlockProps = HTMLAttributes<HTMLPreElement>;

export const CodeBlock = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<CodeBlockProps>, ref: ForwardedRef<HTMLPreElement>) => (
    <pre ref={ref} className={clsx('utrecht-code-block', className)} {...restProps}>
      <code className="utrecht-code-block__content">{children}</code>
    </pre>
  ),
);

CodeBlock.displayName = 'CodeBlock';
