// packages/web-component-library-stencil/src/components/code.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-code',
  styleUrl: 'code.scss',
  shadow: true,
})
export class Code {
  render() {
    return (
      <code class="utrecht-code">
        <slot></slot>
      </code>
    );
  }
}

// packages/component-library-react/src/Code.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type CodeProps = HTMLAttributes<HTMLElement>;

export const Code = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<CodeProps>, ref: ForwardedRef<HTMLElement>) => (
    <code ref={ref} className={clsx('utrecht-code', className)} {...restProps}>
      {children}
    </code>
  ),
);

Code.displayName = 'Code';
