// packages/web-component-library-stencil/src/components/html-content.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2021 Robbert Broersma
 */
import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-html-content',
  styleUrl: 'html-content.scss',
  shadow: false,
})
export class HTMLContent {
  render() {
    return (
      <div class="utrecht-html">
        <slot></slot>
      </div>
    );
  }
}

// packages/component-library-react/src/HTMLContent.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2021 Robbert Broersma
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type HTMLContentProps = HTMLAttributes<HTMLDivElement>;

export const HTMLContent = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<HTMLContentProps>, ref: ForwardedRef<HTMLDivElement>) => (
    <div {...restProps} ref={ref} className={clsx('utrecht-html', className)}>
      {children}
    </div>
  ),
);

HTMLContent.displayName = 'HTMLContent';
