// packages/web-component-library-stencil/src/components/iban-data.stencil.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

const normalizeIBAN = (iban: string): string =>
  iban
    // Remove whitespace and word separator characters such as the dash
    .replace(/[\s+\W]+/g, '')
    .toUpperCase();

const formatIBAN = (normalizedIBAN: string): string =>
  normalizedIBAN
    // Add a space after every four characters, except at the end
    .replace(/(.{4})(?!$)/g, '$1 ');

@Component({
  tag: 'utrecht-iban-data',
  styleUrl: 'iban-data.scss',
  shadow: true,
})
export class IBANData {
  @Prop() value: string;
  render() {
    const { value } = this;
    const normalized = normalizeIBAN(value);
    const formatted = formatIBAN(normalized);
    /*
     * TODO: Add `value={normalized}` attribute when TypeScript definitions for `<data>` allow it
     *
     * Type '{ class: string; value: string; }' is not assignable to type
     * HTMLAttributes<HTMLDataElement>'.Property 'value' does not exist on type 'HTMLAttributes<HTMLDataElement>'.
     */

    /*
     * TODO: Add `translate="no"` when TypeScript definitions allow it
     */
    return <data class="utrecht-iban-data">{formatted}</data>;
  }
}

// packages/component-library-react/src/IBANData.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes } from 'react';

export interface IBANDataProps extends HTMLAttributes<HTMLDataElement> {
  value: string;
}

/* Exported only for unit tests, not part of the public API */
export const normalizeIBAN = (iban: string): string =>
  iban
    // Remove whitespace and word separator characters such as the dash
    .replace(/[\s+\W]+/g, '')
    .toUpperCase();

/* Exported only for unit tests, not part of the public API */
export const formatIBAN = (normalizedIBAN: string): string =>
  normalizedIBAN
    // Add a space after every four characters, except at the end
    .replace(/(.{4})(?!$)/g, '$1 ');

export const IBANData = forwardRef(
  ({ children, value, className, ...restProps }: IBANDataProps, ref: ForwardedRef<HTMLDataElement>) => {
    const normalized = normalizeIBAN(value);
    const formatted = formatIBAN(normalized);

    return (
      <data {...restProps} ref={ref} value={normalized} className={clsx('utrecht-iban-data', className)} translate="no">
        {children || formatted}
      </data>
    );
  },
);

IBANData.displayName = 'IBANData';
