// packages/web-component-library-stencil/src/components/number-value.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-number-value',
  styleUrl: 'number-value.scss',
  shadow: true,
})
export class NumberValue {
  @Prop() value: number | string;
  render() {
    const { value } = this;
    return typeof value === 'number' || typeof value === 'string' ? (
      // <data value={String(value)}>
      <data data-value={String(value)}>
        <slot></slot>
      </data>
    ) : (
      <span>
        <slot></slot>
      </span>
    );
  }
}

// packages/component-library-react/src/NumberValue.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2021 Robbert Broersma
 */

import clsx from 'clsx';
import { DataHTMLAttributes, ForwardedRef, forwardRef, PropsWithChildren } from 'react';

export interface NumberValueProps extends DataHTMLAttributes<HTMLDataElement> {
  value?: number | string;
}

export const NumberValue = forwardRef(
  (
    { children, className, value, ...restProps }: PropsWithChildren<NumberValueProps>,
    ref: ForwardedRef<HTMLDataElement>,
  ) => (
    <data
      value={typeof value === 'string' || typeof value === 'number' ? String(value) : undefined}
      {...restProps}
      ref={ref}
      className={clsx('utrecht-value-number', className)}
    >
      {children}
    </data>
  ),
);

NumberValue.displayName = 'NumberValue';
