// packages/web-component-library-stencil/src/components/page-header.tsx
import { Component, h } from '@stencil/core';

/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

@Component({
  tag: 'utrecht-page-header',
  styleUrl: 'page-header.scss',
  shadow: true,
})
export class PageHeader {
  render() {
    return (
      <header>
        <slot></slot>
      </header>
    );
  }
}

// packages/component-library-react/src/PageHeader.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type PageHeaderProps = HTMLAttributes<HTMLDivElement>;

export const PageHeader = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<PageHeaderProps>, ref: ForwardedRef<HTMLDivElement>) => (
    <header {...restProps} ref={ref} className={clsx('utrecht-page-header', className)}>
      {children}
    </header>
  ),
);

PageHeader.displayName = 'PageHeader';
