// packages/web-component-library-stencil/src/components/pre-heading.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-pre-heading',
  styleUrl: 'pre-heading.scss',
  shadow: true,
})
export class PreHeading {
  render() {
    return (
      <p class="utrecht-pre-heading">
        <slot></slot>
      </p>
    );
  }
}

// packages/component-library-react/src/PreHeading.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type PreHeadingProps = HTMLAttributes<HTMLParagraphElement>;

export const PreHeading = forwardRef(
  (
    { children, className, ...restProps }: PropsWithChildren<PreHeadingProps>,
    ref: ForwardedRef<HTMLParagraphElement>,
  ) => (
    <p {...restProps} ref={ref} className={clsx('utrecht-pre-heading', className)}>
      {children}
    </p>
  ),
);

PreHeading.displayName = 'PreHeading';
