// packages/component-library-react/src/Alert.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren, ReactNode } from 'react';

const enumGuard =
  <T extends unknown>(values: readonly T[]) =>
  (x: unknown): x is T =>
    values.includes(x as T);

export const ROLES = ['status', 'alert'] as const;
export type AlertRole = (typeof ROLES)[number];
export const isAlertRole = enumGuard(ROLES);

export const TYPES = ['error', 'warning', 'info', 'ok'] as const;
export type AlertType = (typeof TYPES)[number];
export const isAlertType = enumGuard(TYPES);

const typeToRole: Record<AlertType, AlertRole> = {
  info: 'status',
  ok: 'status',
  warning: 'alert',
  error: 'alert',
};

export interface AlertProps extends HTMLAttributes<HTMLDivElement> {
  icon?: ReactNode;
  type?: string | AlertType;
  role?: string | AlertRole;
}

export const Alert = forwardRef(
  (
    { children, className, icon, type, role, ...restProps }: PropsWithChildren<AlertProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    const computedType = isAlertType(type) ? type : 'info';
    const computedRole = role || typeToRole[computedType];
    return (
      <div {...restProps} ref={ref} className={clsx('utrecht-alert', `utrecht-alert--${computedType}`, className)}>
        {icon && <div className="utrecht-alert__icon">{icon}</div>}
        <div className="utrecht-alert__content">
          <div className="utrecht-alert__message" role={computedRole}>
            {children}
          </div>
        </div>
      </div>
    );
  },
);

Alert.displayName = 'Alert';

// packages/web-component-library-stencil/src/components/alert.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

const enumGuard =
  <T extends unknown>(values: readonly T[]) =>
  (x: unknown): x is T =>
    values.includes(x as T);

const ROLES = ['status', 'alert'] as const;
type AlertRole = (typeof ROLES)[number];
const isAlertRole = enumGuard(ROLES);

const TYPES = ['error', 'warning', 'info', 'ok'] as const;
type AlertType = (typeof TYPES)[number];
const isAlertType = enumGuard(TYPES);

const typeToRole: Record<AlertType, AlertRole> = {
  info: 'status',
  ok: 'status',
  warning: 'alert',
  error: 'alert',
};

@Component({
  tag: 'utrecht-alert',
  styleUrl: 'alert.scss',
  shadow: true,
})
export class Alert {
  @Prop() type: string;

  render() {
    const computedType = isAlertType(this.type) ? this.type : 'info';
    const computedRole = isAlertRole(typeToRole[computedType]) ? typeToRole[computedType] : 'status';
    return (
      <div class={clsx('utrecht-alert', `utrecht-alert--${computedType}`)}>
        <div class="utrecht-alert__icon">
          <slot name="icon"></slot>
        </div>
        <div class="utrecht-alert__content">
          <div class="utrecht-alert__message" role={computedRole}>
            <slot></slot>
          </div>
        </div>
      </div>
    );
  }
}
