// packages/component-library-react/src/BadgeCounter.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2023 Gemeente Utrecht
 * Copyright (c) 2023 Frameless B.V.
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export interface BadgeCounterProps extends HTMLAttributes<HTMLElement> {
  value?: string;
}

export const BadgeCounter = forwardRef(
  (
    { children, className, value, ...restProps }: PropsWithChildren<BadgeCounterProps>,
    ref: ForwardedRef<HTMLElement | HTMLDataElement>,
  ) => {
    const props = {
      children,
      className: clsx('utrecht-badge-counter', className),
      ...restProps,
    };
    return typeof value !== 'undefined' ? (
      <data {...props} value={value} ref={ref as ForwardedRef<HTMLDataElement>} />
    ) : (
      <span {...props} ref={ref as ForwardedRef<HTMLElement>} />
    );
  },
);

BadgeCounter.displayName = 'BadgeCounter';

// packages/web-component-library-stencil/src/components/badge-counter.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-badge-counter',
  styleUrl: 'badge-counter.scss',
  shadow: true,
})
export class BadgeCounter {
  @Prop() value: number;
  @Prop() max: number;
  @Prop() locale: string;

  render() {
    const { locale, max, value } = this;

    const limited = typeof max === 'number' && typeof value === 'number' && Number(value) > Number(max);
    const formatNumber = (n: number) => (locale ? Intl.NumberFormat(locale).format(n) : String(n));
    const textContent = limited ? `${formatNumber(max)}+` : typeof value === 'number' ? formatNumber(value) : '';

    return <div class="utrecht-badge-counter">{textContent ? textContent : <slot></slot>}</div>;
  }
}
