// packages/component-library-react/src/ButtonGroup.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2021 Robbert Broersma
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, isValidElement, PropsWithChildren, ReactNode } from 'react';

const hasManyElements = (children: ReactNode | ReactNode[]) =>
  Array.isArray(children) &&
  children.reduce((count: number, item): number => (isValidElement(item) ? count + 1 : count), 0) >= 2;

export interface ButtonGroupProps extends HTMLAttributes<HTMLParagraphElement> {
  direction?: string | 'column' | 'row';
}

export const ButtonGroup = forwardRef(
  (
    { children, className, direction, ...restProps }: PropsWithChildren<ButtonGroupProps>,
    ref: ForwardedRef<HTMLParagraphElement>,
  ) => (
    <p
      role={hasManyElements(children) ? 'group' : undefined}
      {...restProps}
      ref={ref}
      className={clsx(
        'utrecht-button-group',
        {
          'utrecht-button-group--column': direction === 'column',
          'utrecht-button-group--row': direction === 'row',
        },
        className,
      )}
    >
      {children}
    </p>
  ),
);

ButtonGroup.displayName = 'ButtonGroup';

// packages/web-component-library-stencil/src/components/button-group.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'utrecht-button-group',
  styleUrl: 'button-group.scss',
  shadow: true,
})
export class ButtonGroup {
  @Prop() direction: string | 'column' | 'row';
  render() {
    const { direction } = this;
    return (
      <div
        class={clsx('utrecht-button-group', {
          'utrecht-button-group--column': direction === 'column',
          'utrecht-button-group--row': direction === 'row',
        })}
      >
        <slot></slot>
      </div>
    );
  }
}
