// packages/component-library-react/src/ColumnLayout.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export interface ColumnLayoutProps extends HTMLAttributes<HTMLDivElement> {
  rule?: boolean;
}

export const ColumnLayout = forwardRef(
  (
    { children, className, rule, ...restProps }: PropsWithChildren<ColumnLayoutProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => (
    <div
      className={clsx('utrecht-column-layout', { 'utrecht-column-layout--rule': rule }, className)}
      ref={ref}
      {...restProps}
    >
      {children}
    </div>
  ),
);

ColumnLayout.displayName = 'ColumnLayout';

// packages/web-component-library-stencil/src/components/column-layout.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-column-layout',
  styleUrl: 'column-layout.scss',
  shadow: true,
})
export class ColumnLayout {
  @Prop({ reflect: true }) rule: boolean = false;
  render() {
    return <slot></slot>;
  }
}
