// packages/component-library-react/src/DataBadge.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export interface DataBadgeProps extends HTMLAttributes<HTMLElement> {
  dateTime?: string;
  value?: string;
}

export const DataBadge = forwardRef(
  (
    { children, className, dateTime, value, ...restProps }: PropsWithChildren<DataBadgeProps>,
    ref: ForwardedRef<HTMLElement | HTMLDataElement>,
  ) => {
    const props = {
      children,
      className: clsx('utrecht-badge-data', className),
      ...restProps,
    };
    return typeof dateTime !== 'undefined' ? (
      <time {...props} dateTime={dateTime} ref={ref as ForwardedRef<HTMLTimeElement>} />
    ) : typeof value !== 'undefined' ? (
      <data {...props} value={value} ref={ref as ForwardedRef<HTMLDataElement>} />
    ) : (
      <span {...props} ref={ref as ForwardedRef<HTMLElement>} />
    );
  },
);

DataBadge.displayName = 'DataBadge';

// packages/web-component-library-stencil/src/components/data-badge.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-data-badge',
  styleUrl: 'data-badge.scss',
  shadow: true,
})
export class DataBadge {
  render() {
    return (
      <div class="utrecht-data-badge">
        <slot></slot>
      </div>
    );
  }
}
