// packages/component-library-react/src/FormFieldTextarea.tsx
import { FormFieldDescription } from '@utrecht/form-field-description-react';
import { FormFieldErrorMessage } from '@utrecht/form-field-error-message-react';
import clsx from 'clsx';
import { ForwardedRef, forwardRef, ReactNode, Ref, useId } from 'react';
import type { FormFieldProps } from './FormField';
import { FormField } from './FormField';
import { FormLabel } from './FormLabel';
import { Textarea } from './Textarea';
import type { TextareaProps } from './Textarea';

export interface FormFieldTextareaProps
  extends Omit<FormFieldProps, 'onBlur' | 'onChange' | 'onFocus' | 'onInput'>,
    Pick<
      TextareaProps,
      | 'autoComplete'
      | 'cols'
      | 'defaultValue'
      | 'disabled'
      | 'invalid'
      | 'maxLength'
      | 'minLength'
      | 'name'
      | 'onBlur'
      | 'onChange'
      | 'onFocus'
      | 'onInput'
      | 'placeholder'
      | 'readOnly'
      | 'required'
      | 'rows'
      | 'value'
    > {
  description?: ReactNode;
  errorMessage?: ReactNode;
  inputDir?: TextareaProps['dir'];
  inputRequired?: TextareaProps['required'];
  label: ReactNode;
  status?: ReactNode;
  inputRef?: Ref<HTMLTextAreaElement>;
}

export const FormFieldTextarea = forwardRef(
  (
    {
      autoComplete,
      children,
      cols,
      defaultValue,
      description,
      disabled,
      errorMessage,
      inputDir,
      inputRequired,
      invalid,
      label,
      maxLength,
      minLength,
      name,
      onBlur,
      onChange,
      onFocus,
      onInput,
      placeholder,
      readOnly,
      required,
      rows,
      status,
      inputRef,
      value,
      ...props
    }: FormFieldTextareaProps,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    const inputId = useId();
    const descriptionId = useId();
    const statusId = useId();
    const errorMessageId = useId();

    return (
      <FormField invalid={invalid} ref={ref} {...props}>
        <div className="utrecht-form-field__label">
          <FormLabel htmlFor={inputId}>{label}</FormLabel>
        </div>
        {description && (
          <FormFieldDescription className="utrecht-form-field__description" id={descriptionId}>
            {description}
          </FormFieldDescription>
        )}
        {invalid && errorMessage && (
          <FormFieldErrorMessage className="utrecht-form-field__error-message" id={errorMessageId}>
            {errorMessage}
          </FormFieldErrorMessage>
        )}
        <div className="utrecht-form-field__input">
          <Textarea
            aria-describedby={
              clsx({
                [descriptionId]: description,
                [errorMessageId]: invalid,
                [statusId]: status,
              }) || undefined
            }
            autoComplete={autoComplete}
            cols={cols}
            defaultValue={defaultValue}
            dir={inputDir}
            disabled={disabled}
            id={inputId}
            inputRequired={inputRequired}
            invalid={invalid}
            maxLength={maxLength}
            minLength={minLength}
            name={name}
            onBlur={onBlur}
            onChange={onChange}
            onFocus={onFocus}
            onInput={onInput}
            placeholder={placeholder}
            readOnly={readOnly}
            ref={inputRef}
            required={required}
            rows={rows}
            value={value}
          />
        </div>
        {status && (
          <div className="utrecht-form-field__status" id={statusId}>
            {status}
          </div>
        )}
        {children}
      </FormField>
    );
  },
);

FormFieldTextarea.displayName = 'FormFieldTextarea';

// packages/web-component-library-stencil/src/components/form-field-textarea.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2021 Robbert Broersma
 */

import { Component, Element, Event, EventEmitter, h, Prop } from '@stencil/core';
import clsx from 'clsx';

const HTML_DEFAULT_COLS = 20;
const HTML_DEFAULT_ROWS = 2;

@Component({
  tag: 'utrecht-form-field-textarea',
  styleUrl: 'form-field-textarea.scss',
  shadow: true,
})
export class FormFieldTextarea {
  @Element() hostElement!: HTMLElement;
  @Prop() cols: number = HTML_DEFAULT_COLS;
  @Prop({ reflect: true }) disabled: boolean = false;
  @Prop({ reflect: true }) invalid: boolean = false;
  @Prop() label: string = '';
  @Prop() name: string = '';
  @Prop({ attribute: 'readonly', reflect: true }) readOnly: boolean = false;
  @Prop() placeholder: string = '';
  @Prop({ reflect: true }) required: boolean = false;
  @Prop() rows: number = HTML_DEFAULT_ROWS;
  @Prop() value: string = '';
  @Event() utrechtBlur: EventEmitter;
  @Event() utrechtChange: EventEmitter;
  @Event() utrechtFocus: EventEmitter;
  @Event() utrechtInput: EventEmitter;

  render() {
    const { cols, disabled, hostElement, invalid, label, name, placeholder, readOnly, required, rows, value } = this;

    let input = hostElement.querySelector('input[type="hidden"]') as HTMLInputElement | null;

    if (input && !name) {
      input.parentNode.removeChild(input);
    }

    if (!input && name) {
      input = hostElement.ownerDocument.createElement('input');
      input.type = 'hidden';
      hostElement.appendChild(input);
    }

    if (input && name) {
      input.name = name;
      input.value = value || '';
    }

    return (
      <div
        class={clsx('utrecht-form-field', 'utrecht-form-field--textbox', {
          'utrecht-form-field--invalid': invalid,
        })}
      >
        <p class="utrecht-form-field__label">
          <label
            class={clsx('utrecht-form-label', {
              'utrecht-form-label--disabled': disabled,
            })}
            htmlFor="input"
          >
            {label}
            <slot name="label"></slot>
          </label>
        </p>
        <utrecht-form-field-description id="description">
          <slot name="description"></slot>
        </utrecht-form-field-description>
        <p class="utrecht-form-field__input">
          <textarea
            id="input"
            class={clsx(
              'utrecht-textarea',
              'utrecht-textarea--html-textarea',
              disabled && 'utrecht-textarea--disabled',
              invalid && 'utrecht-textarea--invalid',
              readOnly && 'utrecht-textarea--readonly',
            )}
            aria-invalid={invalid}
            cols={cols !== HTML_DEFAULT_COLS ? cols : null}
            disabled={disabled}
            dir="auto"
            placeholder={placeholder || null}
            readonly={readOnly}
            required={required}
            rows={rows !== HTML_DEFAULT_ROWS ? rows : null}
            onBlur={(evt) => this.utrechtBlur.emit(evt)}
            onChange={(evt) => this.utrechtChange.emit(evt)}
            onFocus={(evt) => this.utrechtFocus.emit(evt)}
            onInput={(evt) => {
              this.value = (evt.target as HTMLTextAreaElement).value;
              this.utrechtInput.emit(evt);
            }}
          >
            {value}
          </textarea>
        </p>
        {invalid && (
          <utrecht-form-field-description status="invalid" class="utrecht-form-field__error-message" id="error-message">
            <slot name="error-message"></slot>
          </utrecht-form-field-description>
        )}
        <div class="utrecht-form-field__status" id="status">
          <div class="utrecht-form-field-description utrecht-form-field-description--status">
            <slot name="status"></slot>
          </div>
        </div>
      </div>
    );
  }
}
