// packages/component-library-react/src/FormFieldTextbox.tsx
import { FormFieldDescription } from '@utrecht/form-field-description-react';
import { FormFieldErrorMessage } from '@utrecht/form-field-error-message-react';
import clsx from 'clsx';
import { ForwardedRef, forwardRef, PropsWithChildren, ReactNode, Ref, useId } from 'react';
import type { FormFieldProps } from './FormField';
import { FormField } from './FormField';
import { FormLabel } from './FormLabel';
import { Textbox, TextboxProps } from './Textbox';
import { TextboxTypes } from './Textbox';

export interface FormFieldTextboxProps
  extends Omit<FormFieldProps, 'type'>,
    Pick<
      TextboxProps,
      | 'autoComplete'
      | 'defaultValue'
      | 'disabled'
      | 'inputRequired'
      | 'invalid'
      | 'list'
      | 'max'
      | 'maxLength'
      | 'min'
      | 'minLength'
      | 'name'
      | 'pattern'
      | 'placeholder'
      | 'readOnly'
      | 'required'
      | 'size'
      | 'step'
      | 'value'
      | 'type'
    > {
  description?: ReactNode;
  errorMessage?: ReactNode;
  inputDir?: TextboxProps['dir'];
  inputRef?: Ref<HTMLInputElement>;
  label: ReactNode;
  status?: ReactNode;
}

export const FormFieldTextbox = forwardRef(
  (
    {
      name,
      invalid,
      disabled,
      label,
      errorMessage,
      description,
      readOnly,
      status,
      autoComplete,
      list,
      min,
      max,
      minLength,
      maxLength,
      step,
      placeholder,
      pattern,
      required,
      inputRequired,
      inputDir,
      type,
      value,
      onChange,
      onInput,
      onFocus,
      onBlur,
      defaultValue,
      size,
      children,
      inputRef,
      ...props
    }: PropsWithChildren<FormFieldTextboxProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    const inputId = useId();
    const descriptionId = useId();
    const statusId = useId();
    const errorMessageId = useId();

    return (
      <FormField invalid={invalid} ref={ref} {...props}>
        <div className="utrecht-form-field__label">
          <FormLabel htmlFor={inputId}>{label}</FormLabel>
        </div>
        {description && (
          <FormFieldDescription className="utrecht-form-field__description" id={descriptionId}>
            {description}
          </FormFieldDescription>
        )}
        {invalid && errorMessage && (
          <FormFieldErrorMessage className="utrecht-form-field__error-message" id={errorMessageId}>
            {errorMessage}
          </FormFieldErrorMessage>
        )}
        <div className="utrecht-form-field__input">
          <Textbox
            ref={inputRef}
            id={inputId}
            name={name}
            type={(type as TextboxTypes) || 'text'}
            autoComplete={autoComplete}
            aria-describedby={
              clsx({
                [descriptionId]: description,
                [errorMessageId]: invalid,
                [statusId]: status,
              }) || undefined
            }
            invalid={invalid}
            dir={inputDir || 'auto'}
            disabled={disabled}
            min={min}
            max={max}
            minLength={minLength}
            maxLength={maxLength}
            pattern={pattern}
            placeholder={placeholder}
            readOnly={readOnly}
            required={required}
            inputRequired={inputRequired}
            value={value}
            onFocus={onFocus}
            onBlur={onBlur}
            onInput={onInput}
            onChange={onChange}
            defaultValue={defaultValue}
            list={list}
            size={size}
            step={step}
          />
        </div>
        {status && (
          <div className="utrecht-form-field__status" id={statusId}>
            {status}
          </div>
        )}
        {children}
      </FormField>
    );
  },
);

FormFieldTextbox.displayName = 'FormFieldTextbox';

// packages/web-component-library-stencil/src/components/form-field-textbox.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, Element, Event, EventEmitter, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'utrecht-form-field-textbox',
  styleUrl: 'form-field-textbox.scss',
  shadow: true,
})
export class FormFieldTextbox {
  @Element() hostElement!: HTMLElement;

  @Prop({ attribute: 'autocomplete', reflect: true }) autoComplete: string = '';
  @Prop({ reflect: true }) disabled: boolean = false;
  @Prop({ reflect: true }) invalid: boolean = false;
  @Prop() label: string = '';
  @Prop() min: number | string = '';
  @Prop() max: number | string = '';
  @Prop() name: string = '';
  @Prop() pattern: string = '';
  @Prop() placeholder: string = '';
  @Prop({ attribute: 'readonly', reflect: true }) readOnly: boolean = false;
  @Prop({ reflect: true }) required: boolean = false;
  @Prop({ reflect: true }) type: string = '';
  @Prop() value: string = '';
  @Event() utrechtBlur: EventEmitter;
  @Event() utrechtChange: EventEmitter;
  @Event() utrechtFocus: EventEmitter;
  @Event() utrechtInput: EventEmitter;

  render() {
    const {
      autoComplete,
      disabled,
      hostElement,
      invalid,
      label,
      min,
      max,
      name,
      pattern,
      placeholder,
      readOnly,
      required,
      type,
      value,
    } = this;

    let input = hostElement.querySelector('input[type="hidden"]') as HTMLInputElement | null;

    if (input && !name) {
      input.parentNode.removeChild(input);
    }

    if (!input && name) {
      input = hostElement.ownerDocument.createElement('input');
      input.type = 'hidden';
      input.ariaHidden = 'true';
      hostElement.appendChild(input);
    }

    if (input && name) {
      input.name = name;
      input.value = value || '';
    }

    return (
      <div
        class={clsx('utrecht-form-field', 'utrecht-form-field--textbox', {
          'utrecht-form-field--invalid': invalid,
        })}
      >
        <p class="utrecht-form-field__label">
          <label
            class={clsx('utrecht-form-label', {
              'utrecht-form-label--disabled': disabled,
            })}
            htmlFor="input"
          >
            {label}
            <slot name="label"></slot>
          </label>
        </p>
        <utrecht-form-field-description id="description">
          <slot name="description"></slot>
        </utrecht-form-field-description>
        {invalid && (
          <utrecht-form-field-description status="invalid" class="utrecht-form-field__error-message" id="error-message">
            <slot name="error-message"></slot>
          </utrecht-form-field-description>
        )}
        <p class="utrecht-form-field__input">
          <input
            id="input"
            class={clsx(
              'utrecht-form-field__input',
              'utrecht-textbox',
              'utrecht-textbox--html-input',
              disabled && 'utrecht-textbox--disabled',
              invalid && 'utrecht-textbox--invalid',
              readOnly && 'utrecht-textbox--readonly',
            )}
            type={type || 'text'}
            autoComplete={autoComplete ? autoComplete : null}
            aria-describedby={clsx('description', 'status', { 'error-message': invalid })}
            aria-invalid={invalid}
            dir="auto"
            disabled={disabled}
            min={typeof min === 'number' ? String(min) : typeof min === 'string' ? min : null}
            max={typeof max === 'number' ? String(max) : typeof max === 'string' ? max : null}
            pattern={pattern ? pattern : null}
            placeholder={placeholder || null}
            readonly={readOnly}
            required={required}
            value={value}
            onBlur={(evt) => this.utrechtBlur.emit(evt)}
            onChange={(evt) => this.utrechtChange.emit(evt)}
            onFocus={(evt) => this.utrechtFocus.emit(evt)}
            onInput={(evt) => {
              this.value = (evt.target as HTMLInputElement).value;
              this.utrechtInput.emit(evt);
            }}
          />
        </p>
        <div class="utrecht-form-field__status" id="status">
          <div class="utrecht-form-field-description utrecht-form-field-description--status">
            <slot name="status"></slot>
          </div>
        </div>
      </div>
    );
  }
}
