// packages/component-library-react/src/HeadingGroup.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type HeadingGroupProps = HTMLAttributes<HTMLElement>;

export const HeadingGroup = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<HeadingGroupProps>, ref: ForwardedRef<HTMLElement>) => (
    <hgroup {...restProps} ref={ref} className={clsx('utrecht-heading-group', className)}>
      {children}
    </hgroup>
  ),
);

HeadingGroup.displayName = 'HeadingGroup';

// packages/web-component-library-stencil/src/components/heading-group.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h } from '@stencil/core';

@Component({
  tag: 'utrecht-heading-group',
  styleUrl: 'heading-group.scss',
  shadow: true,
})
export class HeadingGroup {
  render() {
    return (
      <hgroup>
        <slot></slot>
      </hgroup>
    );
  }
}
