// packages/component-library-react/src/LinkButton.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ButtonHTMLAttributes, ForwardedRef, forwardRef, PropsWithChildren } from 'react';

export interface LinkButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  inline?: boolean;
  pressed?: boolean;
}

export const LinkButton = forwardRef(
  (
    { children, disabled, inline, className, pressed, type, ...restProps }: PropsWithChildren<LinkButtonProps>,
    ref: ForwardedRef<HTMLButtonElement>,
  ) => (
    <button
      ref={ref}
      aria-pressed={typeof pressed === 'boolean' ? pressed : undefined}
      className={clsx(
        'utrecht-link-button',
        'utrecht-link-button--html-button',
        {
          'utrecht-link-button--disabled': disabled,
          'utrecht-link-button--inline': inline,
          'utrecht-link-button--pressed': pressed,
        },
        className,
      )}
      disabled={disabled}
      type={type || 'button'}
      {...restProps}
    >
      {children}
    </button>
  ),
);

LinkButton.displayName = 'LinkButton';

// packages/web-component-library-stencil/src/components/link-button.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'utrecht-link-button',
  styleUrl: 'link-button.scss',
  shadow: true,
})
export class LinkButton {
  @Prop() disabled: boolean;
  @Prop() type: string;
  @Prop() inline: boolean;
  @Prop() pressed: boolean;
  render() {
    return (
      <button
        class={clsx(
          'utrecht-link-button',
          'utrecht-link-button--html-button',
          this.disabled && 'utrecht-link-button--disabled',
          this.inline && 'utrecht-link-button--inline',
          this.pressed && 'utrecht-link-button--pressed',
        )}
        disabled={this.disabled}
        aria-pressed={typeof this.pressed === 'boolean' ? this.pressed : undefined}
        type={this.type || 'button'}
      >
        <slot></slot>
      </button>
    );
  }
}
