// packages/component-library-vue/src/NumberData.vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "UtrechtNumberData",
  props: {
    value: { type: [Number, String], required: false, default: undefined },
  },
});
</script>

<template>
  <data
    :value="typeof value === 'string' || typeof value === 'number' ? String(value) : undefined"
    class="utrecht-number-data"
  >
    <slot />
  </data>
</template>

<style src="@utrecht/number-data-css/css/index.scss"></style>

// packages/web-component-library-stencil/src/components/number-data.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-number-data',
  styleUrl: 'number-data.scss',
  shadow: true,
})
export class NumberData {
  @Prop() value: number | string;
  render() {
    const { value } = this;
    return typeof value === 'number' || typeof value === 'string' ? (
      // <data value={String(value)}>
      <data data-value={String(value)}>
        <slot></slot>
      </data>
    ) : (
      <span>
        <slot></slot>
      </span>
    );
  }
}
