// packages/component-library-react/src/NumberData.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { DataHTMLAttributes, ForwardedRef, forwardRef, PropsWithChildren } from 'react';

export interface NumberDataProps extends DataHTMLAttributes<HTMLDataElement> {
  value?: number | string;
}

export const NumberData = forwardRef(
  (
    { children, className, value, ...restProps }: PropsWithChildren<NumberDataProps>,
    ref: ForwardedRef<HTMLDataElement>,
  ) => (
    <data
      value={typeof value === 'string' || typeof value === 'number' ? String(value) : undefined}
      {...restProps}
      ref={ref}
      className={clsx('utrecht-number-data', className)}
    >
      {children}
    </data>
  ),
);

NumberData.displayName = 'NumberData';

// packages/web-component-library-stencil/src/components/number-data.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-number-data',
  styleUrl: 'number-data.scss',
  shadow: true,
})
export class NumberData {
  @Prop() value: number | string;
  render() {
    const { value } = this;
    return typeof value === 'number' || typeof value === 'string' ? (
      // <data value={String(value)}>
      <data data-value={String(value)}>
        <slot></slot>
      </data>
    ) : (
      <span>
        <slot></slot>
      </span>
    );
  }
}
