// packages/component-library-react/src/PageContent.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export type PageContentProps = HTMLAttributes<HTMLDivElement>;

export const PageContent = forwardRef(
  ({ children, className, ...restProps }: PropsWithChildren<PageContentProps>, ref: ForwardedRef<HTMLDivElement>) => (
    <div {...restProps} ref={ref} className={clsx('utrecht-page-content', className)}>
      {children}
    </div>
  ),
);

PageContent.displayName = 'PageContent';

export type PageContentMainProps = HTMLAttributes<HTMLDivElement>;

export const PageContentMain = forwardRef(
  (
    { children, className, ...restProps }: PropsWithChildren<PageContentMainProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => (
    <main {...restProps} ref={ref} className={clsx('utrecht-page-content__main', className)}>
      {children}
    </main>
  ),
);

PageContentMain.displayName = 'PageContentMain';

// packages/web-component-library-stencil/src/components/page-content.tsx
import { Component, h } from '@stencil/core';

/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

@Component({
  tag: 'utrecht-page-content',
  styleUrl: 'page-content.scss',
  shadow: true,
})
export class PageContent {
  render() {
    return (
      <div class="utrecht-page-content">
        <main class="utrecht-page-content__main">
          <slot></slot>
        </main>
      </div>
    );
  }
}
