// packages/component-library-vue/src/SkipLink.vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "UtrechtSkipLink",
  props: {
    href: {
      type: String,
      default: undefined,
      required: false,
    },
  },
});
</script>

<template>
  <a v-bind="$attrs" :href="$props.href" class="utrecht-skip-link utrecht-skip-link--visible-on-focus">
    <slot></slot>
  </a>
</template>

<style src="@utrecht/skip-link-css/css/index.scss"></style>

// packages/web-component-library-stencil/src/components/skip-link.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2022 Gemeente Utrecht
 * Copyright (c) 2020-2022 Frameless B.V.
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-skip-link',
  styleUrl: 'skip-link.scss',
  shadow: true,
})
export class SkipLink {
  @Prop() href: string;
  render() {
    return (
      <a
        href={typeof this.href === 'string' ? this.href : undefined}
        class="utrecht-skip-link utrecht-skip-link--visible-on-focus"
      >
        <slot></slot>
      </a>
    );
  }
}
