// packages/component-library-react/src/SpotlightSection.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

/**
 * @deprecated
 */
export type SpotlightSectionType = 'info' | 'warning' | 'error' | 'ok';

/**
 * @deprecated
 */
export interface SpotlightSectionProps extends HTMLAttributes<HTMLDivElement> {
  aside?: boolean;
  type?: string | SpotlightSectionType;
}

/**
 * @deprecated Use `Note` instead, available in `@utrecht/note-react`.
 */
export const SpotlightSection = forwardRef(
  (
    { aside, children, className, type, ...restProps }: PropsWithChildren<SpotlightSectionProps>,
    ref: ForwardedRef<HTMLElement>,
  ) => {
    const props = {
      ...restProps,
      ref,
      className: clsx(
        'utrecht-spotlight-section',
        {
          [`utrecht-spotlight-section--${type}`]: type,
        },
        className,
      ),
    };
    return aside ? <aside {...props}>{children}</aside> : <section {...props}>{children}</section>;
  },
);

SpotlightSection.displayName = 'SpotlightSection';

// packages/web-component-library-stencil/src/components/spotlight-section.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

/**
 * @deprecated Use `Note` instead
 */
@Component({
  tag: 'utrecht-spotlight-section',
  styleUrl: 'spotlight-section.scss',
  shadow: true,
})
export class SpotlightSection {
  @Prop() appearance: string;
  render() {
    return (
      <div
        class={clsx(
          'utrecht-spotlight-section',
          this.appearance === 'error' && 'utrecht-spotlight-section--error',
          this.appearance === 'info' && 'utrecht-spotlight-section--info',
          this.appearance === 'ok' && 'utrecht-spotlight-section--ok',
          this.appearance === 'warning' && 'utrecht-spotlight-section--warning',
        )}
      >
        <slot></slot>
      </div>
    );
  }
}
