// packages/component-library-react/src/StatusBadge.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2023 Gemeente Utrecht
 * Copyright (c) 2023 Frameless B.V.
 */

import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren } from 'react';

export interface StatusBadgeProps extends HTMLAttributes<HTMLElement> {
  status?: string;
}

export const StatusBadge = forwardRef(
  ({ className, status, ...restProps }: PropsWithChildren<StatusBadgeProps>, ref: ForwardedRef<HTMLElement>) => (
    <span
      className={clsx('utrecht-badge-status', `utrecht-badge-status--${status ? status : 'neutral'}`, className)}
      {...restProps}
      ref={ref as ForwardedRef<HTMLElement>}
    />
  ),
);

StatusBadge.displayName = 'StatusBadge';

// packages/web-component-library-stencil/src/components/status-badge.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2020-2024 Frameless B.V.
 * Copyright (c) 2021-2024 Gemeente Utrecht
 */

import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'utrecht-status-badge',
  styleUrl: 'status-badge.scss',
  shadow: true,
})
export class StatusBadge {
  @Prop() status: string;

  render() {
    return (
      <div class={`utrecht-status-badge utrecht-status-badge--${this.status || 'neutral'}`}>
        <slot></slot>
      </div>
    );
  }
}
