// packages/component-library-react/src/BreadcrumbNav.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2021 Robbert Broersma
 */

import clsx from 'clsx';
import { ComponentType, ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren, ReactNode, useId } from 'react';
import { Heading } from './Heading';
import { Link as UtrechtLink } from './Link';

interface BreadcrumbNavProps extends HTMLAttributes<HTMLElement> {
  appearance?: string;
  headingLevel?: number;
  label?: ReactNode | ReactNode[];
}

const useMicrodataItem = ({
  prop,
  type,
}: {
  prop?: string;
  type: string;
}): Pick<HTMLAttributes<HTMLElement>, 'itemProp' | 'itemScope' | 'itemType'> => ({
  itemScope: true,
  itemType: type,
  itemProp: prop,
});

const useMicrodataProp = (prop: string): Pick<HTMLAttributes<HTMLElement>, 'itemProp'> => ({
  itemProp: prop,
});

export const BreadcrumbNav = forwardRef(
  (
    { appearance, children, className, headingLevel = 2, label, ...restProps }: PropsWithChildren<BreadcrumbNavProps>,
    ref: ForwardedRef<HTMLOListElement>,
  ) => {
    const headingId = label ? useId() : undefined;
    return (
      <nav
        {...restProps}
        ref={ref}
        className={clsx(
          'utrecht-breadcrumb',
          {
            'utrecht-breadcrumb--arrows': appearance === 'arrows',
          },
          className,
        )}
        aria-labelledby={headingId}
      >
        {label && (
          <Heading id={headingId} className="utrecht-breadcrumb__heading" level={headingLevel} aria-hidden="true">
            {label}
          </Heading>
        )}
        <ol className="utrecht-breadcrumb__list" {...useMicrodataItem({ type: 'https://schema.org/BreadcrumbList' })}>
          {children}
        </ol>
      </nav>
    );
  },
);

BreadcrumbNav.displayName = 'BreadcrumbNav';

export interface BreadcrumbLinkProps extends HTMLAttributes<HTMLElement> {
  current?: boolean;
  href: string;
  rel?: string;
  index?: number;
  Link?: ComponentType<any>;
}

export const BreadcrumbLink = forwardRef(
  (
    {
      children,
      current,
      href,
      index,
      rel,
      Link = UtrechtLink,
      className,
      ...restProps
    }: PropsWithChildren<BreadcrumbLinkProps>,
    ref: ForwardedRef<HTMLAnchorElement>,
  ) => {
    const DefaultLinkComponent = Link;
    const LinkComponent = Link || DefaultLinkComponent;

    return (
      <li
        className={clsx('utrecht-breadcrumb__item')}
        {...useMicrodataItem({ type: 'https://schema.org/ListItem', prop: 'itemListElement' })}
      >
        <LinkComponent
          className={clsx('utrecht-breadcrumb__link', className, {
            'utrecht-breadcrumb__link--current': current,
          })}
          href={href}
          rel={rel}
          aria-current={current && 'page'}
          {...useMicrodataProp('item')}
          {...restProps}
          ref={ref}
        >
          <span className="utrecht-breadcrumb__text" {...useMicrodataProp('name')}>
            {children}
          </span>
          {typeof index === 'number' ? <meta {...useMicrodataProp('position')} content={String(index + 1)} /> : null}
        </LinkComponent>
      </li>
    );
  },
);

BreadcrumbLink.displayName = 'BreadcrumbLink';

// packages/component-library-vue/src/BreadcrumbNav.vue
<script lang="ts">
  import { defineComponent, getCurrentInstance } from "vue";
  import UtrechtHeading from "./Heading.vue";
  import { useMicrodataItem } from "./helpers/microdata";
  import { useModelWrapper } from "./helpers/modelWrapper";

  export default defineComponent({
    name: "UtrechtBreadcrumbNav",
    components: { UtrechtHeading },
    props: {
      appearance: { type: String, required: false, default: "arrows" },
      headingLevel: { type: Number, required: false, default: 2 },
      label: { type: String, required: false, default: "" },
    },
    setup(props, { emit }) {
      return {
        value: useModelWrapper(props, emit),
      };
    },
    data() {
      return {
        headingId: this.$props.label ? String(getCurrentInstance()?.uid) : undefined,
      };
    },
    methods: { useMicrodataItem, getCurrentInstance },
  });
</script>

<template>
  <nav
    :class="[
      'utrecht-breadcrumb',
      { 'utrecht-breadcrumb-nav--arrows': appearance === 'arrows' },
    ]"
    :aria-labelledby="headingId"
  >
    <UtrechtHeading :id="headingId" class="utrecht-breadcrumb__heading" :level="headingLevel ?? 2" aria-hidden="true">
      {{ label }}
    </UtrechtHeading>

    <ol class="utrecht-breadcrumb__list" v-bind="{...useMicrodataItem({type: 'https://schema.org/BreadcrumbList' })}">
      <slot />
    </ol>
  </nav>
</template>

<style src="@utrecht/components/breadcrumb/css/index.scss"></style>
